name = "shukrinotes"
compatibility_date = "2025-08-19"
main = "src/index.js"
[assets]
directory = "./src/public"
run_worker_first = [
	"/api/*"
]

[[d1_databases]]
binding = "DB"
database_id = "c6f15e25-1804-48f6-b87a-4f593b8a2a91"
database_name = "notes-db"

[[kv_namespaces]]
binding = "NOTES_KV"
id = "71498dac1a70487ba501a8aff1df2724"
preview_id = ""

[[r2_buckets]]
binding = "NOTES_R2_BUCKET"
bucket_name = "notes-r2-bucket"
preview_bucket_name = "notes-files-preview"
